### ISSUE TITLE
Adding profile customization

### ISSUE THREAD

**Issue by aquaticcalf** [flemingslefthandrule/cityvoice#1]
## Requirements:

To implement profile customization, we need to add the following features:
- Avatar Upload: Allow users to upload their own profile pictures or avatars.
- Cover Photo: Provide an option for users to upload a cover photo that appears at the top of their profile page.
- Username Customization: Enable users to choose their own unique username, which will be displayed on their profile page and throughout the app.
- Bio Field: Add a bio field where users can write a short description about themselves.
- Color Scheme Options: Offer a selection of pre-defined color schemes or allow users to choose their own custom colors for their profile page.

Design Requirements:
- The profile page should be redesigned to accommodate the new customization options.
- The avatar upload feature should include image cropping and resizing capabilities.
- The cover photo should be displayed at the top of the profile page, with the option to change the image.
- The username and bio fields should be displayed on the profile page.
- The color scheme options should be easily accessible and applicable to the profile page.

Technical Requirements:
- Update the user model to store the additional profile customization data.
- Implement image upload and storage for avatars and cover photos.
- Develop a username validation system to ensure uniqueness and prevent conflicts.
- Update the profile page template to incorporate the new customization options.

**Comment by MGuruNikhil** [comment]
can i use material ui components and icons
@aquaticcalf

**Comment by aquaticcalf** [comment]
:+1:

**Comment by MGuruNikhil** [comment]
why did u close
